"""Add ...

Revision ID: 2eff6122f882
Revises: 88204114e1af
Create Date: 2025-12-01 13:09:27.667851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eff6122f882'
down_revision: Union[str, Sequence[str], None] = '88204114e1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('Chunk_section_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'Chunk_section_type')
    # ### end Alembic commands ###
