"""remove chunk section ttype 

Revision ID: b7d0583f978e
Revises: 2eff6122f882
Create Date: 2025-12-04 11:47:24.761555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7d0583f978e'
down_revision: Union[str, Sequence[str], None] = '2eff6122f882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_1024_3')
    op.drop_column('chunks', 'Chunk_section_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('Chunk_section_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_table('collection_1024_3',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('collection_1024_3_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_1024_3_pkey'))
    )
    # ### end Alembic commands ###
