"""Add column

Revision ID: c5c169f64080
Revises: 85b76e95c060
Create Date: 2025-11-24 14:11:50.338582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5c169f64080'
down_revision: Union[str, Sequence[str], None] = '85b76e95c060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_1024_5')
    op.drop_table('collection_1024_1')
    op.add_column('assets', sa.Column('asset_doc_type', sa.String(), nullable=False))
    op.add_column('chunks', sa.Column('chunk_doc_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'chunk_doc_type')
    op.drop_column('assets', 'asset_doc_type')
    op.create_table('collection_1024_1',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('collection_1024_1_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_1024_1_pkey'))
    )
    op.create_table('collection_1024_5',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('collection_1024_5_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_1024_5_pkey'))
    )
    # ### end Alembic commands ###
